spring.application.name=civicconnect
spring.datasource.url=jdbc:mysql://localhost:3306/civicconnect_db
spring.datasource.username=root
spring.datasource.password=8090
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true